# Development docker-compose file with server auto-reload and
# code mounted as a volume.
app:
    image: eeacms/eeasearch
    ports: # App accessible on http://localhost:3000
        - 3000:3000
    volumes: # Mount code as a volume for easy restart
        - ./app/:/code/:ro
    environment: # Use current upstream staging instance
        - elastic_host=centaurus-dev.eea.europa.eu
        - elastic_path=/elasticsearch/
        - elastic_port=80
        - NODE_ENV=dev # Change to production if you want to test the app in production environment
        # - SYNC_CRONTAB=30 * * * * # Sync every 30 minutes
